from mentor_whirlpool.telegram import bot
from telebot import asyncio_filters
import mentor_whirlpool.student_handle.ideas
import mentor_whirlpool.student_handle.add_course_work
import mentor_whirlpool.student_handle.delete_course_work
import mentor_whirlpool.student_handle.read_course_works
import mentor_whirlpool.student_handle.start
import mentor_whirlpool.student_handle.wanna_be_mentor

bot.add_custom_filter(asyncio_filters.StateFilter(bot))
bot.add_custom_filter(asyncio_filters.IsDigitFilter())
