name: Nose2 coverage report

on: [push]

env:
  POSTGRE_USER: postgres
  POSTGRE_PASSWD: s3cret
  POSTGRE_ADDRESS: localhost
  POSTGRE_PORT: 5432

jobs:
  database-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3.1.2
      - name: Setup postgresql
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: mentor_whirlpool
          postgresql user: $POSTGRE_USER
          postgresql password: $POSTGRE_PASSWD
      - name: Setup environment
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: bash tests/run_tests.sh
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3.1.2
      - name: Setup postgresql
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: mentor_whirlpool
          postgresql user: postgres
          postgresql password: s3cret
      - name: Setup environment
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: bash tests/run_coverage.sh
      - name: Upload coverage report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: coverage-html
          path: coverage_report
