name: Production deployment

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: sudo apt install ansible
      - name: Deploy
        run: |
          echo "${{ secrets.PRIV_KEY }}" > privkey
          echo "13.80.16.53 ${{ secrets.PUB_KEY }}" > ~/.ssh/known_hosts
          ansible-playbook --private-key privkey -b deployment/playbook.yml -i deployment/inventory
